version: "1.0"

services:
  filmfriend-database:
    container_name: database
    image: orientdb:3.2.16

    environment:
      - ORIENTDB_ROOT_PASSWORD=root
      - ORIENTDB_NODE_NAME=odb1
    ports:
      - "2424:2424"
      - "2480:2480"

  filmfriend-backend:
    container_name: backend
    build: ./backend
    image: backend
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./backend/src/:/usr/src/backend/src
      - ./data/comments:/usr/src/data/comments
      - ./data/processed:/usr/src/data/processed
    # tty: true
    depends_on:
      - filmfriend-database

  filmfriend-frontend:
    container_name: react
    build: ./frontend
    image: frontend
    restart: always
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src/:/usr/src/frontend/src
    depends_on:
      - filmfriend-database
      - filmfriend-backend
    tty: true
