version: "3.0"

services:
  database:
    container_name: filmfriend-database
    image: orientdb:3.2.16
    environment:
      - ORIENTDB_ROOT_PASSWORD=root
      - ORIENTDB_NODE_NAME=odb1
    ports:
      - "2424:2424"
      - "2480:2480"

  backend:
    container_name: filmfriend-backend
    build: ./backend
    image: backend
    restart: on-failure
    ports:
      - "8080:8080"
    volumes:
      - ./backend/src/:/usr/src/backend/src
      - ./data/comments:/usr/src/data/comments
      - ./data/processed:/usr/src/data/processed
    # tty: true
    depends_on:
      - database
    network_mode: host

  frontend:
    container_name: filmfriend-react
    build: ./frontend
    image: frontend
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src/:/usr/src/frontend/src
    depends_on:
      - database
      - backend
    tty: true
